name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and test services
      run: |
        docker compose build
        docker compose up -d
        sleep 30
        
        # Проверяем health endpoints с хоста
        curl -f http://localhost:5000/health || exit 1
        curl -f http://localhost:5001/health || exit 1
        
        docker compose down